// Copyright Nu Quantum Ltd
// Copyright 2026 Shareef Jalloq
// SPDX-License-Identifier: MIT
//
// Auto-generated by peakrdl-sv

package gpio_csr_reg_pkg;

  // Address width
  parameter int BlockAw = 5;


  // gpio_out
  typedef struct packed {
    logic [31:0]q;
  } gpio_csr_reg2hw_gpio_out_t;

  // gpio_oe
  typedef struct packed {
    logic [31:0]q;
  } gpio_csr_reg2hw_gpio_oe_t;

  // gpio_ie
  typedef struct packed {
    logic [31:0]q;
  } gpio_csr_reg2hw_gpio_ie_t;

  // irq_status
  typedef struct packed {
    logic [31:0]q;
  } gpio_csr_reg2hw_irq_status_t;

  // irq_enable
  typedef struct packed {
    logic [31:0]q;
  } gpio_csr_reg2hw_irq_enable_t;

  // irq_edge
  typedef struct packed {
    logic [31:0]q;
  } gpio_csr_reg2hw_irq_edge_t;

  // irq_type
  typedef struct packed {
    logic [31:0]q;
  } gpio_csr_reg2hw_irq_type_t;

  // gpio_out
  typedef struct packed {
    logic [31:0] d;
    logic de;
  } gpio_csr_hw2reg_gpio_out_t;

  // gpio_oe
  typedef struct packed {
    logic [31:0] d;
    logic de;
  } gpio_csr_hw2reg_gpio_oe_t;

  // gpio_in
  typedef struct packed {
    logic [31:0] d;
  } gpio_csr_hw2reg_gpio_in_t;

  // gpio_ie
  typedef struct packed {
    logic [31:0] d;
    logic de;
  } gpio_csr_hw2reg_gpio_ie_t;

  // irq_status
  typedef struct packed {
    logic [31:0] d;
    logic de;
  } gpio_csr_hw2reg_irq_status_t;

  // irq_enable
  typedef struct packed {
    logic [31:0] d;
    logic de;
  } gpio_csr_hw2reg_irq_enable_t;

  // irq_edge
  typedef struct packed {
    logic [31:0] d;
    logic de;
  } gpio_csr_hw2reg_irq_edge_t;

  // irq_type
  typedef struct packed {
    logic [31:0] d;
    logic de;
  } gpio_csr_hw2reg_irq_type_t;


  // Register -> HW
  typedef struct packed {
    gpio_csr_reg2hw_gpio_out_t gpio_out; // 223:192
    gpio_csr_reg2hw_gpio_oe_t gpio_oe; // 191:160
    gpio_csr_reg2hw_gpio_ie_t gpio_ie; // 159:128
    gpio_csr_reg2hw_irq_status_t irq_status; // 127:96
    gpio_csr_reg2hw_irq_enable_t irq_enable; // 95:64
    gpio_csr_reg2hw_irq_edge_t irq_edge; // 63:32
    gpio_csr_reg2hw_irq_type_t irq_type; // 31:0
  } gpio_csr_reg2hw_t;

  // HW -> Register
  typedef struct packed {
    gpio_csr_hw2reg_gpio_out_t gpio_out; // 96:65
    gpio_csr_hw2reg_gpio_in_t gpio_in; // 64:33
    gpio_csr_hw2reg_irq_status_t irq_status; // 32:0
  } gpio_csr_hw2reg_t;

  // Register address offsets
  parameter logic [BlockAw-1:0] GPIO_CSR_GPIO_OUT_OFFSET = 5'h0;
  parameter logic [BlockAw-1:0] GPIO_CSR_GPIO_OE_OFFSET = 5'h4;
  parameter logic [BlockAw-1:0] GPIO_CSR_GPIO_IN_OFFSET = 5'h8;
  parameter logic [BlockAw-1:0] GPIO_CSR_GPIO_IE_OFFSET = 5'hC;
  parameter logic [BlockAw-1:0] GPIO_CSR_IRQ_STATUS_OFFSET = 5'h10;
  parameter logic [BlockAw-1:0] GPIO_CSR_IRQ_ENABLE_OFFSET = 5'h14;
  parameter logic [BlockAw-1:0] GPIO_CSR_IRQ_EDGE_OFFSET = 5'h18;
  parameter logic [BlockAw-1:0] GPIO_CSR_IRQ_TYPE_OFFSET = 5'h1C;

endpackage

