// Copyright Nu Quantum Ltd
// SPDX-License-Identifier: MIT
//
// Auto-generated by peakrdl-sv

package usb_uart_csr_reg_pkg;

  // Address width
  parameter int BlockAw = 5;


  // tx_data
  typedef struct packed {
    logic [31:0]q;
  } usb_uart_csr_reg2hw_tx_data_t;

  // ctrl
  typedef struct packed {
    struct packed {
      logic q;
    } irq_tx_empty_en;
    struct packed {
      logic q;
    } irq_rx_en;
    struct packed {
      logic q;
    } rx_flush;
    struct packed {
      logic q;
    } tx_flush;
    struct packed {
      logic q;
    } thresh_flush_en;
    struct packed {
      logic q;
    } timeout_flush_en;
    struct packed {
      logic q;
    } nl_flush_en;
    struct packed {
      logic q;
    } rx_en;
    struct packed {
      logic q;
    } tx_en;
  } usb_uart_csr_reg2hw_ctrl_t;

  // timeout
  typedef struct packed {
    logic [31:0]q;
  } usb_uart_csr_reg2hw_timeout_t;

  // thresh
  typedef struct packed {
    logic [7:0]q;
  } usb_uart_csr_reg2hw_thresh_t;

  // tx_data
  typedef struct packed {
    logic [31:0] d;
    logic de;
  } usb_uart_csr_hw2reg_tx_data_t;

  // rx_data
  typedef struct packed {
    logic [31:0] d;
  } usb_uart_csr_hw2reg_rx_data_t;

  // rx_len
  typedef struct packed {
    logic [31:0] d;
  } usb_uart_csr_hw2reg_rx_len_t;

  // status
  typedef struct packed {
    struct packed {
      logic [3:0] d;
    } rx_packets;
    struct packed {
      logic [3:0] d;
    } tx_level;
    struct packed {
      logic  d;
    } rx_full;
    struct packed {
      logic  d;
    } rx_valid;
    struct packed {
      logic  d;
    } tx_full;
    struct packed {
      logic  d;
    } tx_empty;
  } usb_uart_csr_hw2reg_status_t;

  // ctrl
  typedef struct packed {
    struct packed {
      logic  d;
      logic de;
    } irq_tx_empty_en;
    struct packed {
      logic  d;
      logic de;
    } irq_rx_en;
    struct packed {
      logic  d;
      logic de;
    } rx_flush;
    struct packed {
      logic  d;
      logic de;
    } tx_flush;
    struct packed {
      logic  d;
      logic de;
    } thresh_flush_en;
    struct packed {
      logic  d;
      logic de;
    } timeout_flush_en;
    struct packed {
      logic  d;
      logic de;
    } nl_flush_en;
    struct packed {
      logic  d;
      logic de;
    } rx_en;
    struct packed {
      logic  d;
      logic de;
    } tx_en;
  } usb_uart_csr_hw2reg_ctrl_t;

  // timeout
  typedef struct packed {
    logic [31:0] d;
    logic de;
  } usb_uart_csr_hw2reg_timeout_t;

  // thresh
  typedef struct packed {
    logic [7:0] d;
    logic de;
  } usb_uart_csr_hw2reg_thresh_t;


  // Register -> HW
  typedef struct packed {
    usb_uart_csr_reg2hw_tx_data_t tx_data; // 80:49
    usb_uart_csr_reg2hw_ctrl_t ctrl; // 48:40
    usb_uart_csr_reg2hw_timeout_t timeout; // 39:8
    usb_uart_csr_reg2hw_thresh_t thresh; // 7:0
  } usb_uart_csr_reg2hw_t;

  // HW -> Register
  typedef struct packed {
    usb_uart_csr_hw2reg_rx_data_t rx_data; // 81:50
    usb_uart_csr_hw2reg_rx_len_t rx_len; // 49:18
    usb_uart_csr_hw2reg_status_t status; // 17:0
  } usb_uart_csr_hw2reg_t;

  // Register address offsets
  parameter logic [BlockAw-1:0] USB_UART_CSR_TX_DATA_OFFSET = 5'h0;
  parameter logic [BlockAw-1:0] USB_UART_CSR_RX_DATA_OFFSET = 5'h4;
  parameter logic [BlockAw-1:0] USB_UART_CSR_RX_LEN_OFFSET = 5'h8;
  parameter logic [BlockAw-1:0] USB_UART_CSR_STATUS_OFFSET = 5'hC;
  parameter logic [BlockAw-1:0] USB_UART_CSR_CTRL_OFFSET = 5'h10;
  parameter logic [BlockAw-1:0] USB_UART_CSR_TIMEOUT_OFFSET = 5'h14;
  parameter logic [BlockAw-1:0] USB_UART_CSR_THRESH_OFFSET = 5'h18;

endpackage

